spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:gieokdama;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/gieokdama"
    username: "root"
    password: "capstone2"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  tomcat:
    max-post-size: 52428800

aws:
  s3:
    bucket-name: "gieokdama-bucket"       # S3 버킷 이름
    region: "ap-northeast-2"             # S3 버킷의 리전 (예: 서울은 ap-northeast-2)
    access-key: "AKIAWAA66CSU262NHTGE"        # AWS 액세스 키
    secret-key: "36AmQ0Bk0yJG6guv4ONxwssG3jywm8Xfii4jB+bn"        # AWS 시크릿 키