name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

    # 3. Remove nohup.out and pull the latest code
    - name: Remove old nohup.out and pull latest code
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /home/ec2-user/CapstoneDesignSpringServer
          rm -f nohup.out
          git pull origin master
        EOF

    # 4. Kill the old process
    - name: Kill old process
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          pkill -f gieokdama-0.0.1-SNAPSHOT.jar || true
        EOF

    # 5. Build the new code
    - name: Build the project
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /home/ec2-user/CapstoneDesignSpringServer
          ./gradlew clean
          ./gradlew build -x test
        EOF

    # 6. Start the new process
    - name: Start the application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /home/ec2-user/CapstoneDesignSpringServer
          nohup java -jar build/libs/gieokdama-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev &
        EOF
